import { type ProjectData } from "./types";

export const projectsData: ProjectData[] = [
  {
    id: "1",
    title: "Fininja",
    desktopImageSrc: "/images/projects/fininja-desktop.png",
    mobileImageSrc: "/images/projects/fininja-mobile.png",
    description: "A personal finance tracker with auto-categorization capibilities.",
    image: "/images/fininja.png",
    demo: "https://app.fininja.ca",
    requestAccess: true,
    stack: [
      "React",
      "Ant Design",
      "Bootstrap",
      "Python",
      "Django",
      "PostgreSQL",
      "Traefik",
      "Docker",
    ],
  },
  {
    id: "2",
    title: "MDS Clear Path",
    desktopImageSrc: "/images/projects/mds-clear-path-desktop.png",
    mobileImageSrc: "/images/projects/mds-clear-path-mobile.png",
    description: "A medical diagnostic tool for a rare blood disorder",
    image: "/images/mds-clear-path.png",
    demo: "https://mdsclearpath.org",
    stack: [
      "React",
      "Ant Design",
      "Bootstrap",
      "Python",
      "Django",
      "PostgreSQL",
      "Traefik",
      "Docker",
      "Jenkins",
    ],
  },
  {
    id: "3",
    title: "ALS Pathways",
    desktopImageSrc: "/images/projects/als-pathways-desktop.png",
    mobileImageSrc: "/images/projects/als-pathways-mobile.png",
    description: "A knowledge base for ALS patients and caregivers",
    image: "/images/als-pathways.png",
    demo: "https://alspathways.ca",
    stack: ["Python", "Wagtail", "PostgreSQL", "Tailwind"],
  },
];
